1. Import numpy

In [5]:
import numpy as np

2. 印出numpy的版本

In [6]:
print(np.__version__)

1.21.6


3. 建立10*5的矩陣，矩陣內的數字皆為0 (5%)


In [ ]:
#印出來的答案應該如下

In [7]:
#輪到你試試看
import numpy as np

print(np.array([
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ]))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


4.建立一個如下的矩陣:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 (5%)

In [32]:
#印出來的答案應該如下

In [8]:
#輪到你試試看
import numpy as np

print(np.array([
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]
    ]))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5.建立一個5*5的單位矩陣 (5%)

In [33]:
#印出來的答案應該如下

In [9]:
#輪到你試試看
import numpy as np

print(np.eye(5, dtype = float))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


6. 做5x4與4*x3矩陣的相乘 (5%)


In [10]:
#印出來的答案可能如下

In [11]:
#輪到你試試看
import numpy as np

A = np.ones((5, 4))
B = np.ones((4, 3))

print(np.dot(A, B))

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


7. 設a為[[1, 0], [1, 2]]的一個矩陣，算出矩陣的determinant (5%)


In [ ]:
#印出來的答案如下

Determinant of the said 2-D array:
2.0


In [12]:
#輪到你試試看
import numpy as np
from numpy import linalg as LA

a = np.array([[1, 0], [1, 2]])
det= LA.det(a)

print("Determinant of the said 2-D array:")
print(det)

Determinant of the said 2-D array:
2.0


8. 得出inverse矩陣 (5%)

In [13]:
import numpy as np

m = np.array([ 
        [1, 2],
        [3, 4]
    ])
result = np.linalg.inv(m)  #請上網尋找如何用numpy得出inverse得出inverse

print("Original matrix:")
print(m)
print("Inverse of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#印出來的參考答案如下

Original matrix:
[[1 2]
 [3 4]]
Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


9. Row operations and elimination (15%)

In [14]:
#不需編撰此處code
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B  

In [15]:
G=np.array([[1,-1,1,3],[2,-2,4,8],[3,0,-9,0]])
print(G)
## Add -2 times row 0 to row 1
G1 = RowAdd(G,0,1,-2)  #fill the code
## Add -3 times row 0 to row 2
G2 = RowAdd(G1,0,2,-3)  #fill the code
## Swap rows 1 and 2
G3 = RowSwap(G2,1,2)  #fill the code
## Scale the new row 1 by 1/3
G4 = RowScale(G3,1,1/3)  #fill the code
## Scale the new row 2 by 1/2
G5 = RowScale(G4,2,1/2)  #fill the code
print(G5)

[[ 1 -1  1  3]
 [ 2 -2  4  8]
 [ 3  0 -9  0]]
[[ 1. -1.  1.  3.]
 [ 0.  1. -4. -3.]
 [ 0.  0.  1.  1.]]


In [ ]:
#印出來的答案如下

[[ 1 -1  1  3]
 [ 2 -2  4  8]
 [ 3  0 -9  0]]
[[ 1. -1.  1.  3.]
 [ 0.  1. -4. -3.]
 [ 0.  0.  1.  1.]]


10. Finding pivots (25%)

In [22]:
G=np.array([[1,-1,1,3],[2,-2,4,8],[3,0,-9,0]])
#利用第九題的def來fill the code

G1 = RowAdd(G,0,1,-2)
G2 = RowAdd(G1,0,2,-3)
G3 = RowScale(G2,2,1/3)
G4 = RowScale(G3,1,1/2)
print(G4)

[[ 1. -1.  1.  3.]
 [ 0.  0.  1.  1.]
 [ 0.  1. -4. -3.]]


In [24]:
G=np.array([[1,-1,1,3],[2,-2,4,8],[3,0,-9,0]])
#利用第九題的def來fill the code

G1 = RowAdd(G,0,1,G[1,0]*(-1))
G2 = RowAdd(G1,0,2,G[2,0]*(-1))
G3 = RowScale(G2,1,1/2)
G4 = RowScale(G3,2,1/3)
print(G4)

[[ 1. -1.  1.  3.]
 [ 0.  0.  1.  1.]
 [ 0.  1. -4. -3.]]


In [ ]:
#印出來的答案如下

[[ 1. -1.  1.  3.]
 [ 0.  0.  1.  1.]
 [ 0.  1. -4. -3.]]


11.找transpose (5%)

In [25]:
A = np.array([[5, 4, 2],[1, 9, 3],[6, 5, 2]])
A_T = np.transpose(A)  #fill the code
print(A_T)

[[5 1 6]
 [4 9 5]
 [2 3 2]]


In [ ]:
#印出來的答案如下

[[5 1 6]
 [4 9 5]
 [2 3 2]]


12. 取出特徵向量與特徵值 (5%)

In [26]:
import numpy as np
from numpy.linalg import eig

a = np.array([[1, 5], 
        [4, 2]])
#complete the code by yourself
val,vec=eig(a)

print('E-value:', val)
print('E-vector', vec)

E-value: [-3.  6.]
E-vector [[-0.78086881 -0.70710678]
 [ 0.62469505 -0.70710678]]


In [ ]:
#印出來的答案如下

E-value: [-3.  6.]
E-vector [[-0.78086881 -0.70710678]
 [ 0.62469505 -0.70710678]]


13. 自己設計一題線性代數的題目，並用python實現 (20%，完成即13%、依題目複雜度給予給予剩下七分)

Let 𝐴 = [[1, 1, 1],[0, 2, 1],[0, 0, 1]] and 𝐛 = [6, 3, 2]
(a) Use the Gram–Schmidt process to find an orthonormal basis for the column 
space of A.
(b) Factor A into a product QR, where Q has an orthonormal set of column 
vectors and R is upper triangular.
(c) Solve the least squares problem 𝐴x = b.

In [60]:
import numpy as np
import numpy.linalg as la

A = np.array([[1, 1, 1],[0, 2, 1],[0, 0, 1]])
B = np.array([6, 3, 2])

Q = np.array(A)

Q[:, 0] = Q[:, 0] / la.norm(Q[:, 0])
Q[:, 1] = Q[:, 1] - Q[:, 1] @ Q[:, 0] * Q[:, 0]
Q[:, 1] = Q[:, 1] / la.norm(Q[:, 1])
Q[:, 2] = Q[:, 2] - Q[:, 2] @ Q[:, 0] * Q[:, 0] - Q[:, 2] @ Q[:, 1] * Q[:, 1]
Q[:, 2] = Q[:, 2] / la.norm(Q[:, 2])

R = np.array(la.inv(Q) @ A)

print('Q = ')
print(Q)

print('R = ')
print(R)

x = la.inv(R) @ (np.transpose(Q) @ B)

print('x = ')
print(x)

Q = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
R = 
[[1. 1. 1.]
 [0. 2. 1.]
 [0. 0. 1.]]
x = 
[3.5 0.5 2. ]
